### PR TITLE
Default email and SMS verification code expiration set to 48 hours

### PR DESCRIPTION
**Pull request by maksim-an-upplabs**
@squallstar @tonytlwu 
## Issue
https://github.com/Fliplet/fliplet-studio/issues/4774
## Description
Added functionality to change verification period by user to minutes, hours, days and weeks also send data in minutes to the backend
## Screenshots/screencasts
https://cl.ly/50c0ec267364
## Backward compatibility
This change is fully backward compatible.

### CODE REVIEW

**Review by tonytlwu — APPROVED** [review]
It's a good implementation. Though, as mentioned in https://github.com/Fliplet/fliplet-studio/issues/4774#issuecomment-520757831 the backend also needs to be updated so that the email sent is also updated with readable units.

@squallstar I'll leave this unmerged. Once you've done the backend work, could you merge this at the same time? I don't think there's a need to pass this back to me to manage.

**Comment by squallstar** [comment]
@sofiiakvasnevska this can't be merged until the backend work outlined by @tonytlwu above is done (I'm the one supposed to do the work).

**Comment by squallstar** [comment]
@sofiiakvasnevska backend work for this has been done. Please check the next steps on the linked issue.

**Review by squallstar — APPROVED** [review]
@sofiiakvasnevska this is ready to be deployed on **staging** for QA.

- **Risk**: Low
- **Affected**: Verification email
- **Verify**: Verify the expiration is using a readable format in the produced email

**Comment by squallstar** [comment]
@sofiiakvasnevska you merged this but it doesn't look like the email template has been updated. Will Upplabs make a new PR to address that? See linked issue for more details.

**Comment by sofiiakvasnevska** [comment]
@squallstar yes, we'll make the PR for it

**Pull request merged**
